language: php

before_install:
  - echo "extension = redis.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini

before_script:
  - phpenv config-rm xdebug.ini

php:
    - 5.5

script:
    - composer install
    - phpunit
